### PR TITLE
Extend unicode-range in CSS to increase emoji coverage

### PR DESCRIPTION
**Pull request by hjalves**
The current `unicode-range` wasn't considering all the existing emojis. One example is the Toolbox emoji: 🧰 (U+1F9F0).

I've made a script that tries to find a more accurate unicode-range, using the emoji-data.txt from unicode.org. Probably there's a better way to do this. https://gist.github.com/hjalves/de890c7842b3143362e1c8ffd668dd15

### CODE REVIEW

**Comment by linusg** [comment]
Interesting, thanks! cc @Xexxa

**Comment by Xexxa** [comment]
Does it make sense including invalid glyphs like 1faff in the unicode-range? 🤔

I'm not sure if it's a wise way to future proof the code or if it can have unintended consequences? @hjalves

**Comment by hjalves** [comment]
> Does it make sense including invalid glyphs like 1faff in the unicode-range? 🤔
> 
> I'm not sure if it's a wise way to future proof the code or if it can have unintended consequences? @hjalves

1faff is being included because of this document: http://www.unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt

`1FAF9..1FAFF  ; Extended_Pictographic# E0.0   [7] (🫹..🫿)    <reserved-1FAF9>..<reserved-1FAFF>`

I think it means that it's currently reserved for future emojis, so I think it's fine to add these.
To be honest, I just worked on a quick and dirty solution that made sense to me, but probably need to research a little bit more.

Do you know any other source where I could find these updated ranges?

**Comment by Xexxa** [comment]
After taking the time and reading the spec I think this is fine!

https://www.w3.org/TR/css-fonts-3/#unicode-range-desc

> The associated font might not contain glyphs for the entire set of codepoints defined by the ‘unicode-range’ descriptor. When the font is used, the effective character map is the intersection of the codepoints defined by ‘unicode-range’ with the font's character map. This allows authors to define supported ranges in terms of broad ranges without worrying about the precise codepoint ranges supported by the underlying font. 

As a hint for the browser the obvious best solution would be to only include the emoji we have in the unicode-range, that would stop the browser from downloading the font in edge cases where someone only use one or more emoji that's not in the font. But my thinking was 1) that seems hard to maintain and 2) we will soon be at 100% coverage.

@hjalves addition of some reserved codepoints does not hurt in any way, it's in fact an improvement of an imperfect solution :-D

**Review by Xexxa — APPROVED** [review]
LGTM

**Comment by linusg** [comment]
Thanks!

**Pull request merged**
